benchmark:
  dataset_registry: config.datasets.example.yaml
  datasets:
    - dataset_id: btc_usdt_1h_v1
      name: BTC_USDT_1h

    - dataset_id: btc_usdt_4h_v1
      name: BTC_USDT_4h

    - dataset_id: eth_usdt_1h_v1
      name: ETH_USDT_1h

    - dataset_id: eth_usdt_4h_v1
      name: ETH_USDT_4h

    - dataset_id: sol_usdt_1h_v1
      name: SOL_USDT_1h

    - dataset_id: sol_usdt_4h_v1
      name: SOL_USDT_4h

  strategies:
    - name: moving_average_cross
      config: config.long.btc.1h.example.yaml

    - name: moving_average_cross_filtered
      config: config.long.btc.1h.filtered.example.yaml

    - name: donchian_breakout
      config: config.long.btc.1h.donchian.example.yaml

    - name: rsi_mean_reversion
      config: config.long.btc.1h.rsi.example.yaml

    - name: bollinger_mean_reversion
      config: config.long.btc.1h.bollinger.example.yaml

    - name: ema_pullback
      config: config.long.btc.1h.ema_pullback.example.yaml
